version: "3.3"

services:
  bot:
    restart: unless-stopped
    build: 
      context: .
      dockerfile: ServerStatusBot/Dockerfile
    network_mode: host
    volumes:
    - "./ServerStatusBot/appsettings.Production.json:/app/appsettings.json"
